---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: producer-example
  namespace: staging
spec:
  template:
    metadata:
      labels:
        app: producer-example
    spec:
      containers:
      - name: producer-example
        command:
        - /bin/sh
        - -c
        - |
          kafka-producer-perf-test \
            --topic producer-example-staging  \
            --record-size 64 \
            --throughput 1 \
            --producer.config /mnt/kafka.properties \
            --num-records 230400
---
# https://docs.confluent.io/operator/current/co-manage-topics.html#create-ak-topic
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: producer-example-staging
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
