apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base
patchesStrategicMerge:
  - producer-app.yaml
  - consumer-app.yaml
patchesJson6902:
  - target:
      group: ""
      version: v1beta1
      kind: KafkaTopic
      name: .*
    patch: |-
      - op: replace                 # patch KafkaTopic namespace to confluent - it MUST be there, and kustomize overrides it to namespace: above
        path: /metadata/namespace
        value: confluent
      - op: replace                 # patch KafkaTopic name for this environment
        path: /metadata/name
        value: example-topic-staging
images:
  - name: keyholesoftware/kafka-consumer
    newName: keyholesoftware/kafka-consumer # {"$imagepolicy": "staging:kafka-service:name"}
    newTag: latest # {"$imagepolicy": "staging:kafka-service:tag"}