apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base
patchesStrategicMerge:
  # - movie-service.yaml
  - producer-app.yaml
patchesJson6902:
  - target:
      group: ""
      version: v1beta1
      kind: KafkaTopic
      name: .*
    patch: |-
      - op: replace                 # patch KafkaTopic namespace to confluent - it MUST be there, and kustomize overrides it to namespace: above
        path: /metadata/namespace
        value: confluent
      - op: replace                 # patch KafkaTopic name for this environment
        path: /metadata/name
        value: simple-producer-staging
# images:
#   - name: ghcr.io/stefanprodan/podinfo
#     newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "staging:podinfo:name"}
#     newTag: 5.0.3 # {"$imagepolicy": "staging:podinfo:tag"}
#   - name: keyholesoftware/movie-service
#     newName: keyholesoftware/movie-service # {"$imagepolicy": "staging:movie-service:name"}
#     newTag: 1.0.0-rc-1657339140 # {"$imagepolicy": "staging:movie-service:tag"}