apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base
  - kafka-topics.yaml
patchesStrategicMerge:
  # - movie-service.yaml
  - producer-app.yaml
# images:
#   - name: ghcr.io/stefanprodan/podinfo
#     newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "staging:podinfo:name"}
#     newTag: 5.0.3 # {"$imagepolicy": "staging:podinfo:tag"}
#   - name: keyholesoftware/movie-service
#     newName: keyholesoftware/movie-service # {"$imagepolicy": "staging:movie-service:name"}
#     newTag: 1.0.0-rc-1657339140 # {"$imagepolicy": "staging:movie-service:tag"}
