apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base
patchesStrategicMerge:
  # - movie-service.yaml
  - producer-app.yaml
patchesJson6902:
  - target:
      group: ""
      version: platform.confluent.io/v1beta1
      kind: KafkaTopic
      name: producer-example-staging
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: confluent
# images:
#   - name: ghcr.io/stefanprodan/podinfo
#     newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "staging:podinfo:name"}
#     newTag: 5.0.3 # {"$imagepolicy": "staging:podinfo:tag"}
#   - name: keyholesoftware/movie-service
#     newName: keyholesoftware/movie-service # {"$imagepolicy": "staging:movie-service:name"}
#     newTag: 1.0.0-rc-1657339140 # {"$imagepolicy": "staging:movie-service:tag"}
