apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: movie-service
spec:
  filterTags:
    pattern: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)-rc-(?P<ts>[1-9][0-9]*)'
    extract: '$ts'
  policy:
     numerical:
      order: asc