# https://docs.confluent.io/operator/current/co-manage-topics.html#create-ak-topic
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: producer-example
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"