apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../base
patchesStrategicMerge: []
patchesJson6902:
  - target:
      group: ""
      version: v1beta1
      labelSelector: "target-namespace=confluent"
      name: .*
    patch: |-
      - op: replace                 # patch KafkaTopic namespace to confluent - it MUST be there, and kustomize overrides it to namespace: above
        path: /metadata/namespace
        value: confluent
images:
  - name: keyholesoftware/kafka-consumer
    newName: keyholesoftware/kafka-consumer # {"$imagepolicy": "production:kafka-consumer:name"}
    newTag: 1.0.0 # {"$imagepolicy": "production:kafka-consumer:tag"}
