apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../base
  - kafka-topics.yaml
patchesStrategicMerge:
  # - movie-service.yaml
  # - producer-app.yaml
patchesJson6902:
  # This keeps all kafka topics in the confluent namespace
  # Otherwise kustomize places them in the namespace: specified above
  - target:
      group: ""
      version: v1beta1
      kind: KafkaTopic
      name: .*
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: confluent
# images:
#   - name: ghcr.io/stefanprodan/podinfo
#     newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "production:podinfo:name"}
#     newTag: 5.0.3 # {"$imagepolicy": "production:podinfo:tag"}
#   - name: keyholesoftware/movie-service
#     newName: keyholesoftware/movie-service # {"$imagepolicy": "production:movie-service:name"}
#     newTag: 1.0.0-rc-1657339140 # {"$imagepolicy": "production:movie-service:tag"}
