apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../base
patchesStrategicMerge:
  - podinfo.yaml
  - producer-app.yaml
  - movie-service.yaml
images:
  - name: ghcr.io/stefanprodan/podinfo
    newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "production:podinfo:name"}
    newTag: 5.0.3 # {"$imagepolicy": "production:podinfo:tag"}
  - name: keyholesoftware/movie-service
    newName: keyholesoftware/movie-service # {"$imagepolicy": "production:movie-service:name"}
    newTag: 1.0.0 # {"$imagepolicy": "production:movie-service:tag"}
