apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: production
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.0.0 # {"$imagepolicy": "production:podinfo"}