

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: staging
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: >-
            keyholesoftware/kafka-consumer:latest
          imagePullPolicy: Always
          env:
          - name: BOOTSTRAP_SERVER
            valueFrom:
              configMapKeyRef:
                name: kafka-client-config
                key: bootstrap.servers
          - name: GROUP_ID
            valueFrom:
              configMapKeyRef:
                name: kafka-client-config
                key: group.id
          - name: TOPIC_NAME
            valueFrom:
              configMapKeyRef:
                name: kafka-client-config
                key: topic
---
# Image repository to watch tags in
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: kafka-consumer
spec:
  image: keyholesoftware/kafka-consumer
  interval: 1m0s
---
# Image policy to update 'patch' versions of keyholesoftware/kafka-consumer image
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: kafka-consumer
spec:
  imageRepositoryRef:
    name: kafka-consumer