# https://docs.confluent.io/operator/current/co-manage-topics.html#create-ak-topic
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: example-topic
  namespace: confluent  # This needs to be in the confluent namespace -- but kustomize will put it in the app namespace, patched in env file
spec:
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
    retention.bytes: "1073741824"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-client-config
data:
  topic: example-topic  # This can get patched in each environment
  bootstrap.servers: kafka.confluent.svc.cluster.local:9092
  group.id: example
  # kafka.properties is used by producer shell script
  kafka.properties: |
    bootstrap.servers=kafka.confluent.svc.cluster.local:9092
    security.protocol=PLAINTEXT