apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-client-config
data:
  topic: producer-example  # This can get patched in each environment
  kafka.properties: |
    bootstrap.servers=kafka.confluent.svc.cluster.local:9071
    security.protocol=PLAINTEXT
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: producer-example
spec:
  serviceName: producer-example
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: producer-example
  template:
    metadata:
      labels:
        app: producer-example
    spec:
      containers:
      - name: producer-example
        image: confluentinc/cp-kafka:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          kafka-producer-perf-test \
            --topic $TOPIC_NAME  \
            --record-size 64 \
            --throughput 1 \
            --producer.config /mnt/kafka.properties \
            --num-records 230400
        env:
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-client-config
              key: topic
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
          readOnly: true
        resources:
          requests:
            memory: 512Mi # 768Mi
            cpu: 500m # 1000m
      volumes:
        - name: kafka-properties # Create secret with name `kafka-client-config` with client configurations
          configMap:
            name: kafka-client-config
---
apiVersion: v1
kind: Service
metadata:
  name: producer-example
spec:
  clusterIP: None

