apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-client-config
data:
  topic: example-topic  # This can get patched in each environment
  bootstrap.servers: kafka.confluent.svc.cluster.local:9092
  group.id: example
  # kafka.properties is used by producer shell script
  kafka.properties: |
    bootstrap.servers=kafka.confluent.svc.cluster.local:9092
    security.protocol=PLAINTEXT
---
# https://docs.confluent.io/operator/current/co-manage-topics.html#create-ak-topic
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: example-topic
  namespace: confluent  # This needs to be in the confluent namespace -- but kustomize will put it in the app namespace, patched in env file
spec:
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
    retention.bytes: 1073741824
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simple-producer
spec:
  serviceName: simple-producer
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: simple-producer
  template:
    metadata:
      labels:
        app: simple-producer
    spec:
      containers:
      - name: simple-producer
        image: confluentinc/cp-kafka:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          kafka-producer-perf-test \
            --topic $TOPIC_NAME  \
            --record-size 64 \
            --throughput 1 \
            --producer.config /mnt/kafka.properties \
            --num-records 230400
        env:
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-client-config
              key: topic
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
          readOnly: true
        resources:
          requests:
            memory: 512Mi # 768Mi
            cpu: 500m # 1000m
      volumes:
        - name: kafka-properties # Create secret with name `kafka-client-config` with client configurations
          configMap:
            name: kafka-client-config
---
apiVersion: v1
kind: Service
metadata:
  name: simple-producer
spec:
  clusterIP: None

